'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class CuicchiGaveglioEntities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=CuicchiGaveglioEntities")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property Bancos() As DbSet(Of Bancos)
    Public Overridable Property Clientes() As DbSet(Of Clientes)
    Public Overridable Property Cobradores() As DbSet(Of Cobradores)
    Public Overridable Property Companias() As DbSet(Of Companias)
    Public Overridable Property Comprobantes() As DbSet(Of Comprobantes)
    Public Overridable Property Estados() As DbSet(Of Estados)
    Public Overridable Property EstadosOperacion() As DbSet(Of EstadosOperacion)
    Public Overridable Property Planillas() As DbSet(Of Planillas)
    Public Overridable Property Roles() As DbSet(Of Roles)
    Public Overridable Property TipoComprobantes() As DbSet(Of TipoComprobantes)
    Public Overridable Property Usuarios() As DbSet(Of Usuarios)

End Class
