'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Planillas
    Public Property idPlanilla As Integer
    Public Property idCliente As Short
    Public Property fPlanilla As Integer
    Public Property idUsuario As Byte
    Public Property idEstadoOperacion As Byte

    Public Overridable Property Clientes As Clientes
    Public Overridable Property Comprobantes As ICollection(Of Comprobantes) = New HashSet(Of Comprobantes)
    Public Overridable Property EstadosOperacion As EstadosOperacion
    Public Overridable Property Usuarios As Usuarios

End Class
