'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Usuarios
    Public Property idUsuario As Byte
    Public Property nombreUsuario As String
    Public Property pass As String
    Public Property idRol As Byte

    Public Overridable Property Comprobantes As ICollection(Of Comprobantes) = New HashSet(Of Comprobantes)
    Public Overridable Property Planillas As ICollection(Of Planillas) = New HashSet(Of Planillas)

End Class
