'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Bancos
    Public Property idBanco As Integer
    Public Property nombreBanco As String

    Public Overridable Property Comprobantes As ICollection(Of Comprobantes) = New HashSet(Of Comprobantes)

End Class
