'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Clientes
    Public Property idCliente As Short
    Public Property nombreCliente As String
    Public Property telefono As String
    Public Property cuit As String
    Public Property dni As String
    Public Property email As String
    Public Property domicilio As String
    Public Property cbu As String
    Public Property obs As String
    Public Property idCobrador As Nullable(Of Short)

    Public Overridable Property Comprobantes As ICollection(Of Comprobantes) = New HashSet(Of Comprobantes)
    Public Overridable Property Cobradores As Cobradores
    Public Overridable Property Planillas As ICollection(Of Planillas) = New HashSet(Of Planillas)

End Class
