'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Cobradores
    Public Property idCobrador As Short
    Public Property nombreCobrador As String

    Public Overridable Property Clientes As ICollection(Of Clientes) = New HashSet(Of Clientes)

End Class
