'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Comprobantes
    Public Property idAlta As Integer
    Public Property idTipoComprobante As Byte
    Public Property fIngreso As Integer
    Public Property idCliente As Short
    Public Property importe As Decimal
    Public Property idEstado As Byte
    Public Property idUsuario As Byte
    Public Property idEstadoOperacion As Byte
    Public Property idCompania As Short
    Public Property idBanco As Integer
    Public Property fPago As Nullable(Of Integer)
    Public Property numero As String
    Public Property obs As String
    Public Property obsBaja As String
    Public Property Tomador As String
    Public Property Ref As String
    Public Property Detalle As String
    Public Property Patente As String
    Public Property FVencimiento As Nullable(Of Integer)
    Public Property idPlanilla As Nullable(Of Integer)

    Public Overridable Property Bancos As Bancos
    Public Overridable Property Clientes As Clientes
    Public Overridable Property Companias As Companias
    Public Overridable Property Estados As Estados
    Public Overridable Property EstadosOperacion As EstadosOperacion
    Public Overridable Property Planillas As Planillas
    Public Overridable Property TipoComprobantes As TipoComprobantes
    Public Overridable Property Usuarios As Usuarios

End Class
